# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
#
############################
# Site wide configurations
############################
title: Random musings
author: devangb
description: > # this means to ignore newlines until "baseurl:"
  Some rants and works
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devangb.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
paginate: 6
paginate_path: "/page/:num/"
gems: [jekyll-paginate]

# Build settings
markdown: kramdown

#
############################
# Site owner configurations
############################
#
owner:
  name: Devangb
  avatar: avatar.jpg
  job: "Programmer & Designer"
  bio: "Computer Science and Engineering, IIT Mandi"
  email: devang.bacharwar@gmail.com
  disqus-shortname:
  twitter: dev_angb
  facebook: devangb0710
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: devangb
  stackoverflow: 2633846/Devang-Bacharwar #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: devangb
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
